# Fish completion for mac-cleans
# Install: cp mac-cleans.fish /usr/local/share/fish/vendor_completions.d/

complete -c mac-cleans -s h -l help -d 'Show help'
complete -c mac-cleans -l version -d 'Show version'
complete -c mac-cleans -l dry-run -d 'Dry run - show what would be deleted'
complete -c mac-cleans -s f -l force -d 'Skip all confirmations'
complete -c mac-cleans -s y -l yes -d 'Skip confirmations (except Xcode)'
complete -c mac-cleans -s i -l interactive -d 'Interactive mode'
complete -c mac-cleans -s j -l json -d 'JSON output'

complete -c mac-cleans -l skip-xcode -d 'Skip Xcode Derived Data'
complete -c mac-cleans -l skip-homebrew -d 'Skip Homebrew cache'
complete -c mac-cleans -l skip-docker -d 'Skip Docker cache'
complete -c mac-cleans -l skip-npm -d 'Skip npm/Yarn cache'
complete -c mac-cleans -l skip-pip -d 'Skip Python pip cache'
complete -c mac-cleans -l skip-chrome -d 'Skip Chrome cache'
complete -c mac-cleans -l skip-firefox -d 'Skip Firefox cache'
complete -c mac-cleans -l skip-edge -d 'Skip Edge cache'
complete -c mac-cleans -l skip-spotify -d 'Skip Spotify cache'
complete -c mac-cleans -l skip-mail -d 'Skip Mail cache'
complete -c mac-cleans -l skip-icloud -d 'Skip iCloud cache'
complete -c mac-cleans -l skip-trash -d 'Skip trash emptying'
complete -c mac-cleans -l skip-gradle -d 'Skip Gradle cache'
complete -c mac-cleans -l skip-bun -d 'Skip Bun cache'
complete -c mac-cleans -l skip-pnpm -d 'Skip pnpm store'
complete -c mac-cleans -l skip-photos -d 'Skip Photos cache'
complete -c mac-cleans -l skip-quicklook -d 'Skip QuickLook cache'
complete -c mac-cleans -l skip-diagnostics -d 'Skip Diagnostic reports'
