# Fish completion for mac-cleans
# Install: cp mac-cleans.fish /usr/local/share/fish/vendor_completions.d/
# shellcheck disable=SC2148

complete -c mac-cleans -s h -l help -d 'Show help'
complete -c mac-cleans -l version -d 'Show version'
complete -c mac-cleans -l dry-run -d 'Dry run - show what would be deleted'
complete -c mac-cleans -s f -l force -d 'Skip all confirmations'
complete -c mac-cleans -s y -l yes -d 'Skip confirmations (except Xcode)'
complete -c mac-cleans -s i -l interactive -d 'Interactive mode'
complete -c mac-cleans -s j -l json -d 'JSON output'
complete -c mac-cleans -s q -l quiet -d 'Minimal output (useful for cron)'
complete -c mac-cleans -l no-color -d 'Disable colored output'
complete -c mac-cleans -s V -l verbose -d 'Enable verbose debug output'
complete -c mac-cleans -s u -l update -d 'Run brew update before cleanup'
complete -c mac-cleans -l threshold -d 'Only run if disk usage is above N%' -r
complete -c mac-cleans -l profile -d 'Use preset profile' -r -a 'conservative developer aggressive minimal'
complete -c mac-cleans -l photos-library -d 'Specify Photos library name or "all"' -r

complete -c mac-cleans -l skip-snapshots -d 'Skip Time Machine snapshots'
complete -c mac-cleans -l skip-homebrew -d 'Skip Homebrew cache'
complete -c mac-cleans -l skip-spotify -d 'Skip Spotify cache'
complete -c mac-cleans -l skip-claude -d 'Skip Claude cache'
complete -c mac-cleans -l skip-xcode -d 'Skip Xcode Derived Data'
complete -c mac-cleans -l skip-xcode-archives -d 'Skip Xcode Archives (release builds + dSYMs)'
complete -c mac-cleans -l skip-browsers -d 'Skip browser cache (Chrome, Firefox, Edge)'
complete -c mac-cleans -l skip-npm -d 'Skip npm/Yarn cache'
complete -c mac-cleans -l skip-pip -d 'Skip Python pip cache'
complete -c mac-cleans -l skip-trash -d 'Skip trash emptying'
complete -c mac-cleans -l skip-dsstore -d 'Skip .DS_Store files'
complete -c mac-cleans -l skip-docker -d 'Skip Docker cache'
complete -c mac-cleans -l skip-simulator -d 'Skip iOS Simulator data'
complete -c mac-cleans -l skip-mail -d 'Skip Mail cache'
complete -c mac-cleans -l skip-siri-tts -d 'Skip Siri TTS cache'
complete -c mac-cleans -l skip-icloud-mail -d 'Skip iCloud Mail cache'
complete -c mac-cleans -l skip-photos-library -d 'Skip Photos Library cache'
complete -c mac-cleans -l skip-icloud-drive -d 'Skip iCloud Drive offline files'
complete -c mac-cleans -l skip-quicklook -d 'Skip QuickLook thumbnails'
complete -c mac-cleans -l skip-diagnostics -d 'Skip Diagnostic reports'
complete -c mac-cleans -l skip-ios-backups -d 'Skip iOS device backups'
complete -c mac-cleans -l skip-ios-updates -d 'Skip iOS update files'
complete -c mac-cleans -l skip-cocoapods -d 'Skip CocoaPods cache'
complete -c mac-cleans -l skip-gradle -d 'Skip Gradle cache'
complete -c mac-cleans -l skip-go -d 'Skip Go module cache'
complete -c mac-cleans -l skip-bun -d 'Skip Bun cache'
complete -c mac-cleans -l skip-pnpm -d 'Skip pnpm store'
complete -c mac-cleans -l skip-browser-tools -d 'Skip browser testing tool caches (puppeteer, selenium)'
complete -c mac-cleans -l skip-crash-reports -d 'Skip crash reports cleanup'
complete -c mac-cleans -l skip-user-tool-caches -d 'Skip user tool caches in ~/.cache/'
complete -c mac-cleans -l skip-jvm -d 'Skip JVM build caches (Maven/Ivy/sbt)'
complete -c mac-cleans -l skip-jetbrains -d 'Skip JetBrains IDE caches (IntelliJ, PyCharm, ...)'
complete -c mac-cleans -l skip-cargo -d 'Skip Cargo registry cache'
complete -c mac-cleans -l skip-system-tmp -d 'Skip /tmp and /var/tmp (default: on)'
complete -c mac-cleans -l clean-system-tmp -d 'Opt in to /tmp and /var/tmp cleanup'

# Register the Mac-Clean alias too, for parity with bash and zsh
complete -c Mac-Clean -w mac-cleans
