# Fish completion for mac-cleans
# Install: cp mac-cleans.fish /usr/local/share/fish/vendor_completions.d/
# shellcheck disable=SC2148

complete -c mac-cleans -s h -l help -d 'Show help'
complete -c mac-cleans -l version -d 'Show version'
complete -c mac-cleans -l dry-run -d 'Dry run - show what would be deleted'
complete -c mac-cleans -s f -l force -d 'Skip all confirmations'
complete -c mac-cleans -s y -l yes -d 'Skip confirmations (except Xcode)'
complete -c mac-cleans -s i -l interactive -d 'Interactive mode'
complete -c mac-cleans -s j -l json -d 'JSON output'

complete -c mac-cleans -l skip-snapshots -d 'Skip Time Machine snapshots'
complete -c mac-cleans -l skip-homebrew -d 'Skip Homebrew cache'
complete -c mac-cleans -l skip-spotify -d 'Skip Spotify cache'
complete -c mac-cleans -l skip-claude -d 'Skip Claude cache'
complete -c mac-cleans -l skip-xcode -d 'Skip Xcode Derived Data'
complete -c mac-cleans -l skip-browsers -d 'Skip browser cache (Chrome, Firefox, Edge)'
complete -c mac-cleans -l skip-npm -d 'Skip npm/Yarn cache'
complete -c mac-cleans -l skip-pip -d 'Skip Python pip cache'
complete -c mac-cleans -l skip-trash -d 'Skip trash emptying'
complete -c mac-cleans -l skip-dsstore -d 'Skip .DS_Store files'
complete -c mac-cleans -l skip-docker -d 'Skip Docker cache'
complete -c mac-cleans -l skip-simulator -d 'Skip iOS Simulator data'
complete -c mac-cleans -l skip-mail -d 'Skip Mail cache'
complete -c mac-cleans -l skip-siri-tts -d 'Skip Siri TTS cache'
complete -c mac-cleans -l skip-icloud-mail -d 'Skip iCloud Mail cache'
complete -c mac-cleans -l skip-photos-library -d 'Skip Photos Library cache'
complete -c mac-cleans -l skip-icloud-drive -d 'Skip iCloud Drive offline files'
complete -c mac-cleans -l skip-quicklook -d 'Skip QuickLook thumbnails'
complete -c mac-cleans -l skip-diagnostics -d 'Skip Diagnostic reports'
complete -c mac-cleans -l skip-ios-backups -d 'Skip iOS device backups'
complete -c mac-cleans -l skip-ios-updates -d 'Skip iOS update files'
complete -c mac-cleans -l skip-cocoapods -d 'Skip CocoaPods cache'
complete -c mac-cleans -l skip-gradle -d 'Skip Gradle cache'
complete -c mac-cleans -l skip-go -d 'Skip Go module cache'
complete -c mac-cleans -l skip-bun -d 'Skip Bun cache'
complete -c mac-cleans -l skip-pnpm -d 'Skip pnpm store'
